name: Continuous Integration

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - "**/README.md"

  pull_request:
    paths-ignore:
      - "**/README.md"

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        action:
          - name: Build Release
            command: build
            args: --release

          - name: Format Check
            command: fmt
            args: --all -- --check --color always

          - name: Clippy
            command: clippy
            args: --all-targets --workspace -- -D warnings

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust ESP toolchain
        uses: esp-rs/xtensa-toolchain@v1.6
        with:
          default: true
          buildtargets: esp32
          ldproxy: true

      - name: Enable caching
        uses: Swatinem/rust-cache@v2

      - name: Run ${{ matrix.action.name }}
        run: cargo ${{ matrix.action.command }} ${{ matrix.action.args }}